V1.2.0

diff --git a/sbfspot-config b/sbfspot-config
--- a/sbfspot-config
+++ b/sbfspot-config
@@ -9,7 +9,7 @@
 #                          |_|                                         |___/ 
 #
 #
-# sbfspot-config V1.1.0
+# sbfspot-config V1.2.0
 # (c) 2017-2020, SBF
 # This tool provides a straight-forward way of doing complete installation
 # and initial configuration of SBFspot/SBFspotUpload on the Raspberry Pi (Raspbian)
@@ -24,18 +24,31 @@
 # curl -s https://raw.githubusercontent.com/sbfspot/sbfspot-config/master/sbfspot-config | sudo bash -s 3.5.0
 
 # Changes:
-# V1.1.0 (14-MAR-2020)
+# V1.2.0 (30-JUN-2020)
+#	- Add: Update SQL DB to required SchemaVersion (SBFspot V3.8.0 needs SchemaVersion 3)
+#
+# V1.1.2 (22-JUN-2020)
+#	- Fix: #21 New install with sbfspot-config fails to unavailable version 3.7.0
+#
+# V1.1.1 (19-JUN-2020)
+#	- Fix: #20 device check returns "Not running on a PI"
+#
+# V1.1.0 (23-MAY-2020)
+#	- Fix: #7 Existing config file overwritten and options missing
 #	- Fix: #10 tar file names contain debian codename to support different raspbian versions (as from SBFspot 3.6.0)
 #	- Fix: installation fails when config file is not in default location and existing config is used
 #	- Fix: when using existing config with MariaDB tool is switching to SQLite
 #	- Fix: daemon fails to start when config file is not in default location
 #	- Fix: Show "Installation failed" when daemon fails to start
-#	- Add: MQTT support
+#	- Add: MQTT support (SBFspot 3.6.0 and higher)
 #	- Fix: #15 crontab deleted
 #	- Fix: #17 missing option for changed inverter password
+#	- Chg: By default, disable CSV export when SQL DB is used
+#	- Add: Run apt-get update if last update was more than one week ago (https://github.com/SBFspot/SBFspot/issues/351)
+#	- Chg: Get events every 5 mins instead of once a day
 #
 # V1.0.15 (20-OCT-2019)
-#	- Fix: #12 Lat/Long Configuration Error when starting with -
+#	- Fix: #12 Lat/Long Configuration Error when starting with '-' character
 #
 # V1.0.14 (28-AUG-2019)
 #	- Fix: Show PVO Error Message
@@ -69,18 +82,18 @@
 
 #set -uo pipefail
 
-readonly toolversion="1.1.0"
+readonly toolversion="1.2.0"
 readonly appname="SBFspot Configuration Tool V$toolversion"
 readonly appshortname="sbfspot-config"
 
 readonly minimum_sbfspot_version="3.5.0"
 
 # default SBFspot parameters used in cron jobs
-readonly p_daydata="-v -ad1 -am0 -ae0"
+readonly p_daydata="-v -ad1 -am0 -ae1"
 readonly p_monthdata="-v -sp0 -ad0 -am1 -ae1 -finq"
 
 # timings used in cron jobs
-readonly t_daydata="*/5 6-22 * * *"	# Every 5 mins from 06:00:00 - 22:59:59
+readonly t_daydata="*/5 6-22 * * *"	# Every 5 mins from 06:00:00 - 22:55:00
 readonly t_monthdata="55 05 * * *"	# Run once a day at 05:55:00
 
 readonly logpath="/var/log/sbfspot.3"
@@ -136,7 +149,7 @@ create_defaults()
 	MIS_Enabled="0"
 	BTConnectRetries="10"
 	
-	CSV_Export="1"
+	CSV_Export="0"
 	OutputPath="$dir_smadata/%Y"
 	OutputPathEvents="$dir_smadata/%Y/Events"
 	CSV_ExtendedHeader="1"
@@ -182,12 +195,6 @@ create_defaults()
 		inv_address="$IP_Address"
 	fi
 
-	if [ "$sql_dbtype" = "NoSQL" ] || [ -z "$PVoutput_Key" ]; then
-		pvo_enabled="0"
-	else
-		pvo_enabled="1"
-	fi
-
 	mqtt_msgformat='json'
 	MQTT_Publisher='/usr/bin/mosquitto_pub'
 	MQTT_Host=''	#'test.mosquitto.org'
@@ -227,14 +234,7 @@ read_defaults()
 		inv_address="$IP_Address"
 	fi
 
-	if [ "$sql_dbtype" = "NoSQL" ] || [ -z "$PVoutput_Key" ]; then
-		pvo_enabled="0"
-	else
-		pvo_enabled="1"
-	fi
-
 	printf "Done\n"
-echo "read_defaults:$dir_smadata"
 }
 
 save_defaults()
@@ -317,8 +317,9 @@ save_defaults()
 search_config()
 {
 	local options
-	local cfglist=$(find / -name SBFspot.cfg 2>/dev/null)
-	if [ ! -z "$cfglist" ]; then
+	local cfglist
+	cfglist=$(find / -name SBFspot.cfg 2>/dev/null)
+	if [ -n "$cfglist" ]; then
 		options=$(echo "$cfglist" | \
 		while read line; do
 			printf '%s\t \toff\n' "$line"
@@ -378,8 +379,8 @@ read_variables()
 		
 		# Surround MQTT_ values with '' to allow special characters like {,"}
 		while IFS='=' read -ra keyvalue; do
-			if [ ! -z "${keyvalue[0]}" ]; then
-				echo "${keyvalue[0]}='${keyvalue[1]}'";
+			if [ -n "${keyvalue[0]}" ]; then
+				echo "${keyvalue[0]}='${keyvalue[1]}'">>"$tempcfg"
 			fi;
 		done <<< $(grep -Po "^MQTT_[aA-zZ_]*=[\" {}aA-zZ0-9/%.,;:-]*" "$cfg")
 
@@ -398,7 +399,7 @@ read_variables()
 		dir_smadata="$userhome/smadata"
 		dir_config="$(dirname "$cfg")"
 
-		if [ ! -z ${LogDir+x} ]; then
+		if [ -n "${LogDir+x}" ]; then
 			dir_logs="$LogDir"
 		fi
 
@@ -417,16 +418,10 @@ read_variables()
 		fi
 		
 		# if database host defined -> MariaDB
-		if [ ! -z "$SQL_Hostname" ]; then
+		if [ -n "$SQL_Hostname" ]; then
 			sql_dbtype="MariaDB"
 		fi
 		
-		if [ "$sql_dbtype" = "NoSQL" ] || [ -z "$PVoutput_Key" ]; then
-			pvo_enabled="0"
-		else
-			pvo_enabled="1"
-		fi
-
 		if [ "$MQTT_ItemDelimiter" = "$mqtt_json_itemdelimiter" ] && [ "$MQTT_ItemFormat" = "$mqtt_json_itemformat" ] && [ "$MQTT_PublisherArgs" = "$mqtt_json_publisherargs" ]; then
 			mqtt_msgformat='json'
 		elif [ "$MQTT_ItemDelimiter" = "$mqtt_xml_itemdelimiter" ] && [ "$MQTT_ItemFormat" = "$mqtt_xml_itemformat" ] && [ "$MQTT_PublisherArgs" = "$mqtt_xml_publisherargs" ]; then
@@ -504,12 +499,16 @@ get_releases()
 		url="${url: : -1}"
 	fi
 
+	# download releases page from Github
 	wget -qNP "$tmppath" "$url"
 	
 	if [ -f "$tmppath/releases" ]; then
-		local rlist=($(grep -Po "(\d+\.)(\d+\.)(\d)/.*\.gz" "$tmppath/releases"))
+		local rlist
+		# Get available versions for codename (stretch/buster/...)
+		rlist=($(grep -Po "(\d+\.)(\d+\.)(\d)/.*\-$lsb_codename\.tar\.gz" "$tmppath/releases"))
 		
-		local min_version_value=$(vvalue $minimum_sbfspot_version)
+		local min_version_value
+		min_version_value=$(vvalue $minimum_sbfspot_version)
 		
 		for (( i=0; i<${#rlist[@]}; i++ )); do
 			local version=$(echo "${rlist[$i]}"|awk '/$/ { print $1 }' FS='/')
@@ -531,7 +530,9 @@ get_releases()
 
 is_pi()
 {
-	grep -q "^model name\\s*:\\s*ARMv" /proc/cpuinfo
+	# Fix #20
+	#grep -q "^model name\\s*:\\s*ARMv" /proc/cpuinfo
+	grep -aq "^Raspberry Pi" /proc/device-tree/model
 	return $?
 }
 
@@ -670,6 +671,7 @@ do_db_config()
 	local tmp_SQL_Password="$SQL_Password"
 
 	local db_choice="$sql_dbtype"
+	local tmp_CSV_Export="$CSV_Export"
 	local rc=0
 	
 	db_choice=$(get_option $'SQLite\tRecommended\nMariaDB\tConnect to MySQL/MariaDB server\nNoSQL\tNo database - CSV only' "$db_choice" "Database Configuration")
@@ -683,6 +685,7 @@ do_db_config()
 		SQL_Hostname="$tmp_SQL_Hostname"
 		SQL_Username="$tmp_SQL_Username"
 		SQL_Password="$tmp_SQL_Password"
+		CSV_Export="$tmp_CSV_Export"
 		return
 	fi
 
@@ -697,6 +700,7 @@ do_db_config()
 		SQL_Hostname=""
 		SQL_Username=""
 		SQL_Password=""
+		CSV_Export="0"
 		whiptail --msgbox "SQLite has no configurable options." 0 0
 	fi
 
@@ -707,6 +711,7 @@ do_db_config()
 #			SQL_Hostname="localhost"
 #			SQL_Username="SBFspotUser"
 #			SQL_Password="SBFspotPassword"
+#			CSV_Export="0"
 #		fi
 #		do_mysql_config
 #	fi
@@ -718,6 +723,7 @@ do_db_config()
 			SQL_Hostname="localhost"
 			SQL_Username="SBFspotUser"
 			SQL_Password="SBFspotPassword"
+			CSV_Export="0"
 		fi
 		do_mysql_config
 	fi
@@ -732,12 +738,6 @@ do_db_config()
 		whiptail --msgbox "SQL export disabled.\nOutput will be written to CSV files\nUpload to PVOutput disabled" 0 0
 	fi
 
-	if [ "$sql_dbtype" = "NoSQL" ] || [ -z "$PVoutput_Key" ]; then
-		pvo_enabled="0"
-	else
-		pvo_enabled="1"
-	fi
-echo "do_db_config:$SQL_Database"
 }
 
 do_mysql_config()
@@ -915,8 +915,24 @@ do_install()
 		read -r -a sv <<< $(grep -P "^SchemaVersion\s*\d*" $tmp_dir/sqldb.test)
 		local schemaversion=${sv[1]}
 		
-		# TODO: Validate SchemaVersion
 		echo "Schema Version=$schemaversion"
+
+		if [ "$schemaversion" -lt 3 ] && [ "$(vvalue $version_wanted)" -ge "$(vvalue '3.8.0')" ]; then
+			if [ "$dbtype" = "sqlite" ]; then
+				echo "Updating database to Version 3..."
+				cd "$dir_smadata"
+				sqlite3 SBFspot.db < "$tmp_dir/Update_V2_SQLite.sql"
+				sqlite3 SBFspot.db < "$tmp_dir/Update_V3_SQLite.sql"
+			fi
+			
+			# User is responsible for update of SBFspot db
+			if [ "$dbtype" = "mariadb" ]; then
+				whiptail --msgbox "There is a problem:\nIncorrect Schema Version\n\nDid you update the SBFspot database?\n$dbtype < $dir_program/Update_V2_MySQL.sql\n$dbtype < $dir_program/Update_V3_MySQL.sql" 0 0
+				echo "Incorrect Schema Version"
+				echo "Installation aborted"
+				return 255
+			fi
+		fi
 	fi
 
 	if [ "$mqtt_enabled" -eq 1 ]; then
@@ -933,7 +949,7 @@ do_install()
 	cd "$dir_config"
 	
 	if [ -f "$sbfspotcfg" ]; then
-		printf "Saving existing $sbfspotcfg... "
+		printf "Saving existing %s... " "$sbfspotcfg"
 		local backup_cfg="$sbfspotcfg.$(date +%Y%m%d_%H%M%S)"
 		cp "$sbfspotcfg" "$backup_cfg"
 		chown "$username:$username" "$backup_cfg"
@@ -965,14 +981,14 @@ do_install()
 		echo "#                                                                               "
 		echo "#    SMA and Speedwire are registered trademarks of SMA Solar Technology AG     "
 		echo "################################################################################"
-		echo "#"
+		echo ""
 		echo "# $sbfspotcfg - Created $(date) with $appshortname V$toolversion"
 		echo ""
 
 		# Configure Bluetooth
 		if [ "$inv_connectiontype" = "Bluetooth" ]; then
 			echo "# SMA Inverter's Bluetooth address"
-			echo "# Windows: smaspot -scan"
+			echo "# Windows: sbfspot -scan"
 			echo "# Linux  : hcitool scan"
 			echo "BTAddress=$BTAddress"
 			echo ""
@@ -991,6 +1007,7 @@ do_install()
 			echo "# BTConnectRetries"
 			echo "# Number of Bluetooth Connection attempts (1-15; Default=10)"
 			echo "BTConnectRetries=$BTConnectRetries"
+			echo ""
 		fi
 		
 		# Configure Speedwire
@@ -1000,15 +1017,18 @@ do_install()
 			echo "# If IP_Address is set to a valid IP, SBFspot will try to connect directly to that IP without broadcast detection"
 			echo "# Multiple IP addresses can be provided (comma separated)"
 			echo "IP_Address=$IP_Address"
+			echo ""
 		fi
 		
 		# Configure User Password
 		echo "# User password (default 0000)"
 		echo "Password=$Password"
+		echo ""
 
 		# Configure Plant Name
 		echo "# Plantname"
 		echo "Plantname=$Plantname"
+		echo ""
 		
 		# Configure where to store CSV files
 		echo "# OutputPath (Place to store CSV files)"
@@ -1016,6 +1036,7 @@ do_install()
 		echo "# Linux  : /home/pi/smadata/%Y"
 		echo "# %Y %m and %d will be expanded to Year Month and Day"
 		echo "OutputPath=$OutputPath"
+		echo ""
 		
 		echo "# OutputPathEvents (Place to store CSV files for events)"
 		echo "# If omitted, OutputPath is used"
@@ -1189,7 +1210,7 @@ do_install()
 			echo "# InvType         NameplateModel      Device type"
 			echo "# InvSwVer        NameplatePkgRev     Software package"
 			echo "# InvStatus       OperationHealth     Condition"
-			echo "# InvTemperature  CoolsysTmpNom       Operating condition temperatures"
+			echo "# InvTemperature  CoolsysTmpNom       Operating condition temperature"
 			echo "# InvGridRelay    OperationGriSwStt   Grid relay/contactor"
 			echo "# ETotal          MeteringTotWhOut    Total yield"
 			echo "# EToday          MeteringDyWhOut     Day yield"
@@ -1213,6 +1234,7 @@ do_install()
 			echo "# BatVol          BatVol              Battery voltage"
 			echo "# BatAmp          BatAmp              Battery current"
 			echo "# BatChaStt       BatChaStt           Current battery charge status"
+			echo ""
 		fi
 
 		echo "# End of Config"
@@ -1220,13 +1242,16 @@ do_install()
 	
 	printf "Done\n"
 	
+	local mqtt_arg=""
+	[ "$mqtt_enabled" -eq 1 ] && mqtt_arg=" -mqtt"
+
 	# launch script for daydata (every 5 minutes)
 	local daydata="$dir_program/daydata"
 	{
 		echo "#!/bin/bash"
 		echo "#"
 		echo "log=$dir_logs/${Plantname}_\$(date '+%Y%m%d').log"
-		echo "$dir_program/SBFspot $p_daydata -cfg$dir_config/$sbfspotcfg \$1 \$2 \$3 \$4 \$5 &>>\$log"
+		echo "$dir_program/SBFspot $p_daydata$mqtt_arg -cfg$dir_config/$sbfspotcfg \$1 \$2 \$3 \$4 \$5 &>>\$log"
 	} >"$daydata"
 	
 	chmod +x "$daydata"
@@ -1542,19 +1567,23 @@ check_pvo_key_sid()
 
 do_pvo_config()
 {
+	# PVO upload is only available with SQL DB
+	if [ "$sql_dbtype" = "NoSQL" ]; then
+		whiptail --msgbox "PVoutput upload is not possible without SQL DB" 0 0
+		return
+	fi
+
 	# backup current settings
 	local tmp_PVoutput_SID="$PVoutput_SID"
 	local tmp_PVoutput_Key="$PVoutput_Key"
-	local tmp_pvo_enabled="$pvo_enabled"
 
 	local rc=0
 	local opt
 
 	while true; do
 		opt=$(whiptail --title "PVOutput Configuration" --menu "" 0 70 0 --cancel-button "OK" --ok-button "Select" \
-			"1 Upload to PVOutput : " $(on_off_status "$tmp_pvo_enabled") \
-			"2 System ID (SID)    : " "$tmp_PVoutput_SID" \
-			"3 API Key            : " "$tmp_PVoutput_Key" \
+			"1 System ID (SID)    : " "$tmp_PVoutput_SID" \
+			"2 API Key            : " "$tmp_PVoutput_Key" \
 			3>&1 1>&2 2>&3)
 		
 		rc=$?
@@ -1563,13 +1592,10 @@ do_pvo_config()
 			return
 		elif [ $rc -eq 0 ]; then # Select/Enter
 			case "$opt" in
-				1\ *) tmp_pvo_enabled=$(get_option $'0\tOff\n1\tOn' "$tmp_pvo_enabled" "Upload to PVOutput" \
-						"Enables or disables the PVOutput Upload functionality\nThis requires a free PVOutput.org account\n") ;;
-				2\ *) tmp_PVoutput_SID=$(get_input "Enter PVOutput SystemID's (comma separated)" "$tmp_PVoutput_SID") ;;
-				3\ *) tmp_PVoutput_Key=$(get_input "Enter 40-character API Key (case sensitive)" "$tmp_PVoutput_Key") ;;
+				1\ *) tmp_PVoutput_SID=$(get_inputx "Enter PVOutput SystemID's (comma separated)" "$tmp_PVoutput_SID" "" "^($|[0-9]+|[0-9]+(,[0-9]+)*)$" "Invalid") ;;
+				2\ *) tmp_PVoutput_Key=$(get_inputx "Enter 40-character API Key" "$tmp_PVoutput_Key" "" "^([0-9a-f]{40})?$" "Invalid") ;;
 			esac
 		elif [ $rc -eq 1 ]; then # OK
-			pvo_enabled="$tmp_pvo_enabled"
 			PVoutput_SID="$tmp_PVoutput_SID"
 			PVoutput_Key="$tmp_PVoutput_Key"
 			cfg_dirty=1
@@ -1580,6 +1606,13 @@ do_pvo_config()
 
 do_mqtt_config()
 {
+	# MQTT is supported as from SBFspot V3.6.0
+	# Do nothing if installing lower version
+	if [ "$mqtt_enabled" -lt 0 ]; then
+		whiptail --msgbox "MQTT is not supported in SBFspot V$version_wanted\nInstall V3.6.0 or higher" 0 0
+		return
+	fi
+	
 	# Copy current settings
 	local tmp_MQTT_Publisher="$MQTT_Publisher"
 	local tmp_MQTT_Host="$MQTT_Host"
@@ -1743,6 +1776,48 @@ get_input()
 	else
 		echo "$2"			# ESC
 	fi
+	
+	return $rc
+}
+
+# extended version of get_input
+# uses regex validation pattern
+get_inputx()
+{
+	# $1 Message to display
+	# $2 Current Value
+	# $3 Title (optional)
+	# $4 regex validation pattern (optional)
+	# $5 validation error message (optional)
+	
+	local tmp_input="$2"
+	local rc=0
+	local waiting=1
+	local msg="$1"
+	
+	while [ "$waiting" -eq 1 ]; do
+		if [ -z "$3" ]; then
+			tmp_input=$(whiptail --inputbox "$msg" 0 0 -- "$tmp_input" 3>&1 1>&2 2>&3)
+		else
+			tmp_input=$(whiptail --inputbox --title "$3" "$msg" 0 0 -- "$tmp_input" 3>&1 1>&2 2>&3)
+		fi
+	
+		rc=$?
+
+		if [ "$rc" -eq 0 ]; then
+			if [[ "$tmp_input" =~ $4 ]]; then
+				echo "$tmp_input" # OK
+				waiting=0
+			else
+				if [ ! -z "$5" ]; then
+					msg="$1\n\n$5"
+				fi
+			fi
+		else
+			echo "$2" # ESC, return default value
+			waiting=0
+		fi
+	done
 	
 	return $rc
 }
@@ -2085,7 +2160,7 @@ on_off_status()
 	elif [ "$1" -eq 1 ]; then
 		echo "On"
 	else
-		echo "?"
+		echo "N/A"
 	fi
 }
 
@@ -2176,6 +2251,10 @@ install_pkg()
 	rc=$?
 	
 	if [ "$rc" -ne 0 ]; then	# Package not installed
+		# Run apt-get update if last update was more than one week ago
+		# https://askubuntu.com/questions/410247/how-to-know-last-time-apt-get-update-was-executed/904259#904259
+		[ -z "$(find -H /var/lib/apt/lists -maxdepth 0 -mtime -7)" ] && apt-get update
+		
 		apt-get -y install "$package"
 		dpkg -s "$package" &>/dev/null
 		rc=$?
@@ -2263,34 +2342,11 @@ do_preinstallcheck()
 	#	return 1
 	#fi
 
-	if [ "$pvo_enabled" -eq 1 ]; then
-		if [ -z "$PVoutput_Key" ] || [ -z "$PVoutput_SID" ]; then
-			whiptail --msgbox "PVoutput enabled, but API key and/or SystemID missing" 0 0
-			return 1
-		fi
-	fi
-		
 	# TODO: Add other checks
 	
 	printf "Done\n"
 	
 	return 0 #OK
-}
-
-# Check if an element is in array
-# contains "an item" "${array[@]}"
-# returns 0 if array contains item, or 1 if not
-contains()
-{
-	local e match="$1"
-	shift
-	for e; do [[ "$e" = "$match" ]] && return 0; done
-	return 1
-}
-
-debug_trace()
-{
-	echo "$1"
 }
 
 # Main starts here
@@ -2328,7 +2384,7 @@ echo "userhome=$userhome"
 : ${version_wanted:=$(get_latest_release)}
 
 if [ -z "$version_wanted" ]; then
-	echo "Error: Unable to get available versions"
+	echo "Error: Unable to get list of available SBFspot versions for '$lsb_codename'"
 	exit 1
 fi
 
@@ -2342,8 +2398,7 @@ fi
 
 # Get available versions
 ver_avail=$(get_releases)
-contains "$version_wanted" ${ver_avail[@]}
-if [ "$?" = "1" ]; then
+if [[ ! " ${ver_avail[@]} " =~ " ${version_wanted} " ]]; then
 	echo "Version $version_wanted is not available for installation."
 	echo "Select one of $ver_avail"
 	exit 1
@@ -2353,6 +2408,8 @@ cfg_dirty=0
 mkdir -p "$tmppath"
 read_variables
 rc=$?
+
+db_backup_warning=0
 
 export NEWT_COLORS=''
 
@@ -2368,12 +2425,30 @@ if [ "$rc" -eq 0 ]; then
 			db_on_server="$sql_dbtype"
 		fi
 		
-		# When MQTT_Host is filled in, assume MQTT enabled
-		if [ -z "$MQTT_Host" ]; then
+		# MQTT is supported as from SBFspot V3.6.0
+		if [ "$(vvalue $version_wanted)" -lt "$(vvalue '3.6.0')" ]; then
+			mqtt_enabled=-1	# MQTT N/A
+		elif [ -z "$MQTT_Host" ]; then
 			mqtt_enabled=0
 		else
 			mqtt_enabled=1
 		fi;
+		
+		# Set PVOutput status
+		if [ "$sql_dbtype" = "NoSQL" ]; then
+			pvo_enabled=-1	# PVO N/A
+		elif [ -z "$PVoutput_Key" ] || [ -z "$PVoutput_SID" ]; then
+			pvo_enabled=0
+		else
+			pvo_enabled=1
+		fi
+		
+		# When installing V3.8.0 or up, warn user about database upgrade
+		if [ "$db_backup_warning" -eq 0 ] && [ "$sql_dbtype" != "NoSQL" ] && [ "$(vvalue $version_wanted)" -ge "$(vvalue '3.8.0')" ]; then
+			db_backup_warning=1
+			whiptail --msgbox --title "* * * WARNING! * * *" "Installing V$version_wanted requires an important database update.\nIt is highly recommended to take a backup of the database.\nOnce updated, there is no way back." 0 0
+		fi
+
 
 		opt=$(whiptail \
 			--title "$appname" \
